### ISSUE TITLE
u-swipe-action-item 组件 在H5 ”other.js“ 报 ” this.setStatus is not a function “

### ISSUE THREAD

**Issue by dengciping0716** [ijry/uview-plus#264]
bug表现为两个操作按钮只显示了一个。
version: 3.1.42
浏览器：edge

错误信息：
vue.runtime.esm.js:1439  Uncaught TypeError: this.setStatus is not a function
    at Proxy.openSwipeAction (other.js?v=61a0cdb3:135:9)
    at Proxy.touchend (other.js?v=61a0cdb3:120:11)
    at callWithErrorHandling (vue.runtime.esm.js:1375:22)
    at callWithAsyncErrorHandling (vue.runtime.esm.js:1384:21)
    at HTMLElement.invoker (vue.runtime.esm.js:9730:9)

**Comment by ijry** [comment]
今晚更新修复
