### ISSUE TITLE
<u-sticky> 报错

### ISSUE THREAD

**Issue by wm1234566** [ijry/uview-plus#27]
u-sticky.vue:42 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'guid')
    at Proxy.data (u-sticky.vue:42:18)
    at Proxy.mergedDataFn (vue.runtime.esm.js:5003:92)
    at applyOptions (vue.runtime.esm.js:4694:34)
    at finishComponentSetup (vue.runtime.esm.js:8629:9)
    at setupStatefulComponent (vue.runtime.esm.js:8541:9)
    at setupComponent (vue.runtime.esm.js:8463:11)
    at mountComponent (vue.runtime.esm.js:6808:13)
    at processComponent (vue.runtime.esm.js:6783:17)
    at patch (vue.runtime.esm.js:6367:21)
    at mountChildren (vue.runtime.esm.js:6564:13)

**Comment by ijry** [comment]
请提供，HBuilderX版本、操作系统、是否cli方式
