### ISSUE TITLE
android 真机运行时，$u 变量不存在的问题

### ISSUE THREAD

**Issue by littleBoBoy** [ijry/uview-plus#41]
http.ts 文件中对uni.$u.http进行了封装，api.ts 中使用了http.ts 暴露的方法定义了接口。
在.vue 页面中import这个方法并没有调用，运行到真机后 报错
```javascript
reportJSException >>>> exception function:createInstanceContext, exception:white screen cause create instanceContext failed,check js stack ->Uncaught TypeError: Cannot read property 'http' of undefined
 at  (app-service.js:3672:23)
 at  (app-service.js:9906:3)
```
但是使用nvue的页面引入没问题

uniapp 编译器版本：3.6.8（vue3）

uview-plus 3.1.16

**Comment by ijry** [comment]
$U的用法在uni-app(vue3)中存在兼容性问题，待官方解决。
