### ISSUE TITLE
cli 方式 app-plus 运行到手机端报错

### ISSUE THREAD

**Issue by dodu2014** [ijry/uview-plus#80]
如题，cli 方式 app-plus 运行到手机端报错，如下：

```
reportJSException >>>> exception function:createInstanceContext, exception:white screen cause create instanceContext failed,check js stack ->Uncaught TypeError: Cannot read property 'mpMixin' of undefined
 at  (app-service.js:16263:21)
 at  (app-service.js:27792:3)
```

**Comment by ijry** [comment]
运行到安卓成功
<img width="1191" alt="image" src="https://user-images.githubusercontent.com/3102798/212619591-2a3c1631-0390-4ac4-b691-9b81f77ab879.png">

**Comment by dodu2014** [comment]
你用的模拟器吗，我是自定义基座，运行到真机

**Comment by dodu2014** [comment]
<img width="1234" alt="image" src="https://user-images.githubusercontent.com/15245544/212694815-41797009-6296-4b20-b2bf-67c8da8ac690.png">

**Comment by dodu2014** [comment]
给 package 依赖贴出来你看看

```json
  "dependencies": {
    "@dcloudio/uni-app": "3.0.0-alpha-3070020230114001",
    "@dcloudio/uni-app-plus": "3.0.0-alpha-3070020230114001",
    "@dcloudio/uni-components": "3.0.0-alpha-3070020230114001",
    "@dcloudio/uni-h5": "3.0.0-alpha-3070020230114001",
    "@dcloudio/uni-i18n": "3.0.0-alpha-3070020230114001",
    "@dcloudio/uni-mp-alipay": "3.0.0-alpha-3070020230114001",
    "@dcloudio/uni-mp-baidu": "3.0.0-alpha-3070020230114001",
    "@dcloudio/uni-mp-kuaishou": "3.0.0-alpha-3070020230114001",
    "@dcloudio/uni-mp-lark": "3.0.0-alpha-3070020230114001",
    "@dcloudio/uni-mp-qq": "3.0.0-alpha-3070020230114001",
    "@dcloudio/uni-mp-toutiao": "3.0.0-alpha-3070020230114001",
    "@dcloudio/uni-mp-weixin": "3.0.0-alpha-3070020230114001",
    "@dcloudio/uni-quickapp-webview": "3.0.0-alpha-3070020230114001",
    "@fortawesome/fontawesome-free": "^6.2.1",
    "@iconify/iconify": "^3.0.1",
    "clipboard": "^2.0.11",
    "crypto-js": "^4.1.1",
    "dayjs": "^1.11.7",
    "echarts": "^5.4.1",
    "lodash-es": "^4.17.21",
    "luch-request": "^3.0.8",
    "pinia": "^2.0.28",
    "qs": "^6.11.0",
    "uview-plus": "^3.1.23",
    "vue": "^3.2.45",
    "vue-i18n": "^9.1.9"
  },
  "devDependencies": {
    "@dcloudio/types": "^3.2.7",
    "@dcloudio/uni-automator": "3.0.0-alpha-3070020230114001",
    "@dcloudio/uni-cli-shared": "3.0.0-alpha-3070020230114001",
    "@dcloudio/uni-stacktracey": "3.0.0-alpha-3070020230114001",
    "@dcloudio/vite-plugin-uni": "3.0.0-alpha-3070020230114001",
    "@iconify/json": "^2.2.6",
    "@types/crypto-js": "^4.1.1",
    "@types/lodash-es": "^4.17.6",
    "@types/node": "^17.0.45",
    "@types/qs": "^6.9.7",
    "@typescript-eslint/eslint-plugin": "^5.48.1",
    "@typescript-eslint/parser": "^5.48.1",
    "@unocss/preset-icons": "^0.46.5",
    "autoprefixer": "^10.4.13",
    "eslint": "^8.31.0",
    "eslint-config-prettier": "^8.6.0",
    "eslint-plugin-prettier": "^4.2.1",
    "eslint-plugin-vue": "^9.9.0",
    "husky": "^8.0.3",
    "lint-staged": "^13.1.0",
    "mrm": "^4.1.13",
    "postcss": "^8.4.21",
    "prettier": "^2.8.3",
    "sass": "^1.57.1",
    "sass-loader": "10",
    "typescript": "^4.9.4",
    "unocss": "^0.46.5",
    "unocss-preset-weapp": "^0.2.5",
    "unplugin-vue-components": "^0.22.12",
    "vite": "^4.0.4",
    "vite-plugin-eslint": "^1.8.1"
  },
```

**Comment by ZXQ2023** [comment]
我找到组件中uni.$u.mpMixin替换成mpMixin就可以了,为何没挂载上去还没看出来

**Comment by ijry** [comment]
> 我找到组件中uni.$u.mpMixin替换成mpMixin就可以了,为何没挂载上去还没看出来

uni-app官方3.0对Mixin的支持还有问题。

**Comment by osenx** [comment]
插眼

**Comment by osenx** [comment]
![image](https://user-images.githubusercontent.com/22234240/217983625-f80c2722-7ab0-46a5-b5dc-8bdc79026a71.png)
